# Generated by Django 4.0.4 on 2022-06-21 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название напитка')),
                ('img', models.FileField(upload_to='drink/', verbose_name='Фото напитка')),
                ('description', models.CharField(max_length=500, verbose_name='Описание напитка')),
                ('price', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='в Наличии')),
                ('new_price', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Напитки',
                'verbose_name_plural': 'Напитки',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название еды')),
                ('img', models.FileField(upload_to='food/', verbose_name='Фото еды')),
                ('description', models.CharField(max_length=500, verbose_name='Описание еды')),
                ('price', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='в Наличии')),
                ('new_price', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_page.food')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
