# Generated by Django 4.0.6 on 2022-07-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='в Наличии'),
        ),
        migrations.AddField(
            model_name='drink',
            name='new_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание еды'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='img',
            field=models.FileField(upload_to='food/', verbose_name='Фото еды'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название еды'),
        ),
    ]
