# Generated by Django 4.0.4 on 2022-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='в Наличии')),
                ('price', models.IntegerField(null=True)),
                ('new_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='drink',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='price',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='food',
            name='new_price',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
