# Generated by Django 4.0.6 on 2022-07-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_drink_amount_drink_is_available_drink_new_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание Напитка'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='img',
            field=models.FileField(upload_to='drink/', verbose_name='Фото Напитка'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название Напитка'),
        ),
    ]
