# Generated by Django 4.0.4 on 2022-06-23 12:37

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_price_remove_drink_amount_remove_drink_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Is_available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='в Наличии')),
            ],
        ),
        migrations.CreateModel(
            name='NewPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='price',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='price',
            name='new_price',
        ),
        migrations.AddField(
            model_name='food',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='в Наличии'),
        ),
        migrations.AddField(
            model_name='food',
            name='new_price',
            field=models.IntegerField(null=True, verbose_name=main_page.models.NewPrice),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(null=True, verbose_name=main_page.models.Price),
        ),
        migrations.AlterField(
            model_name='food',
            name='amount',
            field=models.IntegerField(null=True, verbose_name=main_page.models.Amount),
        ),
    ]
